[package]
name = "tailor-server-redis"
version = "0.1.0"
edition = "2021"
author = "Guillaume Heu"

[dependencies]
rocket = { version= "0.5.0-rc.1"}
serde = {version= "1.0", features= ["derive"]}
serde_json = "1.0.79"
lazy_static = "1.4.0"
handlebars = "4.2.2"